In [1]:
import pandas as pd
import numpy as nm
import statsmodels.stats as sm
import scipy
from scipy.optimize import linprog

In [3]:
stargas_entire = pd.ExcelFile("StarGas - All Traffic Sources.xlsx")
stargas = stargas_entire.parse('abc')

In [4]:
stargas.head()

Traffic_Source MediaType       Date                             Device  \
0        Adwords       SEM 2016-01-01                          Computers   
1        Adwords       SEM 2016-01-01  Mobile devices with full browsers   
2        Adwords       SEM 2016-01-01         Tablets with full browsers   
3        Adwords       SEM 2016-01-02                          Computers   
4        Adwords       SEM 2016-01-02  Mobile devices with full browsers   

   Clicks  Impressions  Actual_Spend  Conversions Traffic_Source_Final  
0     124        15696        389.22          7.0              Adwords  
1     195        10540        643.87         11.0              Adwords  
2      67         4468        220.83          4.0              Adwords  
3     181        19544        537.48         11.0              Adwords  
4     306        14584       1062.53          9.0              Adwords

In [5]:
stargas.columns

Index(['Traffic_Source', 'MediaType', 'Date', 'Device', 'Clicks',
       'Impressions', 'Actual_Spend', 'Conversions', 'Traffic_Source_Final'],
      dtype='object')

In [6]:
stargas['Device'].head()

0                            Computers
1    Mobile devices with full browsers
2           Tablets with full browsers
3                            Computers
4    Mobile devices with full browsers
Name: Device, dtype: object

In [7]:
stargas['Device'].value_counts()

Computers                            816
Tablets with full browsers           816
Mobile devices with full browsers    816
Computer                             520
Smartphone                           224
Tablet                               119
Name: Device, dtype: int64

In [8]:
stargas['MediaType'].value_counts()

SEM             4126
Display          737
Social Media     535
Name: MediaType, dtype: int64

In [9]:
stargas.drop('MediaType',axis=1,inplace=True)
#Delete column from the data set 


In [10]:
stargas.drop('Device', axis=1,inplace=True)

In [11]:
stargas.drop('Traffic_Source',axis=1,inplace=True)

In [12]:

stargas.drop('Traffic_Source_Final', axis=1,inplace=True)

In [13]:

stargas.drop('Date', axis=1,inplace=True)

In [14]:
stargas.drop('Year', axis=1,inplace=True)

KeyError: "labels ['Year'] not contained in axis"

In [15]:
stargas.drop('Month', axis=1,inplace=True)

KeyError: "labels ['Month'] not contained in axis"

In [16]:
stargas.drop('Clicks', axis=1,inplace=True)

In [17]:
stargas.drop('Impressions', axis=1,inplace=True)

In [18]:
stargas.drop('Actual_Spend', axis=1,inplace=True)

In [19]:
stargas.drop('Conversions', axis=1,inplace=True)

In [20]:
Traffic=stargas.groupby('Traffic_Source_Final') 

KeyError: 'Traffic_Source_Final'

In [21]:
Traffic_counts=Traffic.aggregate(sum)

NameError: name 'Traffic' is not defined

In [22]:
Traffic_counts

NameError: name 'Traffic_counts' is not defined

In [23]:
Traffic_counts.drop('Month',axis=1,inplace=True)

NameError: name 'Traffic_counts' is not defined

In [24]:
Traffic_counts

NameError: name 'Traffic_counts' is not defined

In [25]:
(Traffic_counts['Clicks'])/(Traffic_counts['Actual_Spend']) #calculating Clicks per spend of each channel

NameError: name 'Traffic_counts' is not defined

In [26]:
Media=stargas.groupby('MediaType')

KeyError: 'MediaType'

In [27]:
Media_counts=Media.aggregate(sum)

NameError: name 'Media' is not defined

In [28]:
Media_counts

NameError: name 'Media_counts' is not defined

In [29]:
Month=stargas.groupby('Month')

KeyError: 'Month'

In [30]:
Month_counts=Month.aggregate(sum)

NameError: name 'Month' is not defined

In [31]:
Month_counts


NameError: name 'Month_counts' is not defined

In [32]:
Month_counts.index=MONTH_WISE

NameError: name 'MONTH_WISE' is not defined

In [33]:
Month_counts.index=[1,2,3,4,5,6,7,8,9,10,11,12]

NameError: name 'Month_counts' is not defined

In [34]:
Month_counts['Conversions']

NameError: name 'Month_counts' is not defined

In [35]:
Impressions_perSpend=Month_counts['Impressions']/Month_counts['Actual_Spend']

NameError: name 'Month_counts' is not defined

In [36]:
Month_cond=Month_counts.index<4

NameError: name 'Month_counts' is not defined

In [37]:
Month_counts[Month_cond]['Clicks']/3


NameError: name 'Month_counts' is not defined

In [38]:
Month_cond=Month_counts.index>3

NameError: name 'Month_counts' is not defined

In [39]:
Month_counts[Month_cond]['Clicks']/2

NameError: name 'Month_counts' is not defined

In [40]:
Conversion_per_spendM=Month_counts['Conversions']/Month_counts['Actual_Spend']

NameError: name 'Month_counts' is not defined

In [41]:
Conversion_per_spendM

NameError: name 'Conversion_per_spendM' is not defined

In [42]:
Impressions_perSpend.plot(kind='bar',figsize=(15,10),title="Clicks per spend")

NameError: name 'Impressions_perSpend' is not defined

In [43]:
Conversion_per_spendM.plot(kind='bar',figsize=(15,10),title="Conversions per spend")

NameError: name 'Conversion_per_spendM' is not defined

In [44]:
Conversion_per_spendM.plot(figsize=(15,10),title="Conversions per Spend")

NameError: name 'Conversion_per_spendM' is not defined

In [45]:
PPC1 #pay per click

NameError: name 'PPC1' is not defined

In [46]:
CPI1=sum(stargas[jan]['Actual_Spend'])/sum(stargas[jan]['Impressions'])   #cost per impression

NameError: name 'jan' is not defined

In [47]:
CPI1

NameError: name 'CPI1' is not defined

In [48]:
PPC2=sum(stargas[feb]['Actual_Spend'])/sum(stargas[feb]['Clicks'])

NameError: name 'feb' is not defined

In [49]:
PPC2

NameError: name 'PPC2' is not defined

In [50]:
CPI2=sum(stargas[feb]['Actual_Spend'])/sum(stargas[feb]['Impressions'])

NameError: name 'feb' is not defined

In [51]:
CPI2

NameError: name 'CPI2' is not defined

In [52]:
PPC3=sum(stargas[mar]['Actual_Spend'])/sum(stargas[mar]['Clicks'])

NameError: name 'mar' is not defined

In [53]:
PPC3

NameError: name 'PPC3' is not defined

In [54]:
CPI3=sum(stargas[mar]['Actual_Spend'])/sum(stargas[mar]['Impressions'])

NameError: name 'mar' is not defined

In [55]:
CPI3

NameError: name 'CPI3' is not defined

In [56]:
PPC4=sum(stargas[april]['Actual_Spend'])/sum(stargas[april]['Clicks'])

NameError: name 'april' is not defined

In [57]:
PPC4

NameError: name 'PPC4' is not defined

In [58]:
CPI4=sum(stargas[april]['Actual_Spend'])/sum(stargas[april]['Impressions'])

NameError: name 'april' is not defined

In [59]:
CPI4

NameError: name 'CPI4' is not defined

In [60]:
PPC5=sum(stargas[may]['Actual_Spend'])/sum(stargas[may]['Clicks'])

NameError: name 'may' is not defined

In [61]:
PPC5

NameError: name 'PPC5' is not defined

In [62]:
CPI5=sum(stargas[may]['Actual_Spend'])/sum(stargas[april]['Impressions'])

NameError: name 'may' is not defined

In [63]:
CPI5

NameError: name 'CPI5' is not defined

In [64]:
PPC6=sum(stargas[june]['Actual_Spend'])/sum(stargas[june]['Clicks'])

NameError: name 'june' is not defined

In [65]:
PPC6

NameError: name 'PPC6' is not defined

In [66]:
CPI6=sum(stargas[june]['Actual_Spend'])/sum(stargas[june]['Impressions'])

NameError: name 'june' is not defined

In [67]:
CPI6

NameError: name 'CPI6' is not defined

In [68]:
PPC7=sum(stargas[july]['Actual_Spend'])/sum(stargas[july]['Clicks'])

NameError: name 'july' is not defined

In [69]:
PPC7

NameError: name 'PPC7' is not defined

In [70]:
CPI7=sum(stargas[july]['Actual_Spend'])/sum(stargas[july]['Impressions'])

NameError: name 'july' is not defined

In [71]:
CPI7

NameError: name 'CPI7' is not defined

In [72]:
PPC8=sum(stargas[aug]['Actual_Spend'])/sum(stargas[aug]['Clicks'])

NameError: name 'aug' is not defined

In [73]:
PPC8

NameError: name 'PPC8' is not defined

In [74]:
CPI8=sum(stargas[aug]['Actual_Spend'])/sum(stargas[aug]['Impressions'])

NameError: name 'aug' is not defined

In [75]:
CPI8

NameError: name 'CPI8' is not defined

In [76]:
PPC9=sum(stargas[sep]['Actual_Spend'])/sum(stargas[sep]['Clicks'])

NameError: name 'sep' is not defined

In [77]:
PPC9

NameError: name 'PPC9' is not defined

In [78]:
CPI9=sum(stargas[sep]['Actual_Spend'])/sum(stargas[sep]['Impressions'])

NameError: name 'sep' is not defined

In [79]:
CPI9

NameError: name 'CPI9' is not defined

In [80]:
PPC10=sum(stargas[october]['Actual_Spend'])/sum(stargas[october]['Clicks'])

NameError: name 'october' is not defined

In [81]:
PPC10

NameError: name 'PPC10' is not defined

In [82]:
CPI10=sum(stargas[october]['Actual_Spend'])/sum(stargas[october]['Impressions'])

NameError: name 'october' is not defined

In [83]:
CPI10

NameError: name 'CPI10' is not defined

In [84]:
PPC11=sum(stargas[nov]['Actual_Spend'])/sum(stargas[nov]['Clicks'])

NameError: name 'nov' is not defined

In [85]:
PPC11

NameError: name 'PPC11' is not defined

In [86]:
CPI11=sum(stargas[nov]['Actual_Spend'])/sum(stargas[nov]['Impressions'])

NameError: name 'nov' is not defined

In [87]:
CPI11

NameError: name 'CPI11' is not defined

In [88]:
PPC12=sum(stargas[dec]['Actual_Spend'])/sum(stargas[dec]['Clicks'])

NameError: name 'dec' is not defined

In [89]:
PPC12

NameError: name 'PPC12' is not defined

In [90]:
CPI12=sum(stargas[dec]['Actual_Spend'])/sum(stargas[dec]['Impressions'])

NameError: name 'dec' is not defined

In [91]:
CPI12

NameError: name 'CPI12' is not defined

In [92]:
MONTH_WISE=['JAN','FEB','MAR','APRIL','MAY','JUNE','JULY','AUG','SEP','OCT','NOV','DEC']

In [93]:
Group1=list(zip(PPC,CPI)) 

NameError: name 'PPC' is not defined

In [94]:
table1=pd.DataFrame(data=Group1,columns=['PPC','CPI'],index=MONTH_WISE)

NameError: name 'Group1' is not defined

In [95]:
table1.head(12) # pay per clicks and cost per impression month wise

NameError: name 'table1' is not defined

In [96]:
Device=stargas.groupby('Device')

KeyError: 'Device'

In [97]:
Device_counts=Device.aggregate(sum)

NameError: name 'Device' is not defined

In [98]:
Device_counts

NameError: name 'Device_counts' is not defined

In [99]:
Month_counts.plot(kind='bar',tick_label=MONTH_WISE,figsize=(15,10))

NameError: name 'Month_counts' is not defined

In [100]:
Month_counts.plot(kind='bar',tick_label=MONTH_WISE,figsize=(15,10))

NameError: name 'Month_counts' is not defined

In [101]:
stargas['Device'].value_counts().plot(kind='bar')

KeyError: 'Device'

In [102]:
Device_counts.plot(kind='bar',figsize=(15,10))

NameError: name 'Device_counts' is not defined

In [103]:

%matplotlib inline

In [104]:
Month_counts['Clicks'].plot(figsize=(15,10))

NameError: name 'Month_counts' is not defined

In [ ]:
Month_counts['Clicks'].plot(kind='bar',figsize=(15,10),title="Clicks per Month")

In [ ]:
Month_counts['Impressions'].plot(figsize=(15,10))

In [ ]:
Month_counts['Impressions'].plot(kind='bar',figsize=(15,10))

In [ ]:
Month_counts['Actual_Spend'].plot(figsize=(15,10))

In [105]:
Month_counts['Actual_Spend'].plot(kind='bar',figsize=(15,10))

NameError: name 'Month_counts' is not defined

In [106]:
Device_counts['Conversions'].plot(kind='bar',figsize=(15,10))

NameError: name 'Device_counts' is not defined

In [107]:
Device_counts['Clicks'].plot(kind='bar',figsize=(15,10))

NameError: name 'Device_counts' is not defined

In [108]:
Device_counts['Impressions'].plot(kind='bar',figsize=(15,10))

NameError: name 'Device_counts' is not defined

In [109]:
Device_counts['Actual_Spend'].plot(kind='bar',figsize=(15,10))

NameError: name 'Device_counts' is not defined

In [110]:
Media_groups = stargas.groupby('MediaType')

KeyError: 'MediaType'

In [111]:
Media_groups.get_group('SEM')

NameError: name 'Media_groups' is not defined

In [112]:
Traffic = stargas.groupby('Traffic_Source_Final')

KeyError: 'Traffic_Source_Final'

In [113]:
Traffic_counts=Traffic.aggregate(sum)

NameError: name 'Traffic' is not defined

In [114]:
cond=stargas['Year']==17

KeyError: 'Year'

In [115]:
Traffic_counts

NameError: name 'Traffic_counts' is not defined

In [116]:
#Linear Programming Model

In [117]:
c = [-0.01649546,-0.00673206,-0.00210477,-0.00554307]
A= [[1.0,1.0,1.0,1.0],[-10.6287265,0.0,0.0,0.0],[0.0,-14.7469492,0.0,0.0],[0.0,0.0,-87.0776054,0.0],[0.0,0.0,0.0,-43.6720415],
    [-0.20812002,0.0,0.0,0.0],[0.0,-0.27602498,0.0,0.0],[0.0,0.0,-0.04120044,0.0],[0.0,0.0,0.0,-0.49814672],[-0.01649546,0.0,0.0,0.0],[0.0,-0.00673206,0.0,0.0],[0.0,0.0,-0.00210477,0.0],[0.0,0.0,0.0,-0.00554307]]
b= [1000000.0,-1000000.0,-1000000.0,-1000000.0,-100000.0,-500.0,-500.0,-500.0,-500.0,-100.0,-100.0,-100.0,-100.0]

In [118]:
x1_bounds=[10000,None]
x2_bounds=[10000,None]
x3_bounds=[10000,None]
x4_bounds=[10000,None]


In [120]:
res = linprog(c,A_ub=A,b_ub=b,bounds=(x1_bounds,x2_bounds,x3_bounds,x4_bounds),options={"disp": True},method='interior-point')

Primal Feasibility  Dual Feasibility    Duality Gap         Step             Path Parameter      Objective          
1.0                 1.0                 0.96912464          -                1.0                 -2208.505704564     
5.136111438588e-05  5.136111614919e-05  4.512768186893e-05  0.9999486388856  5.136111083895e-05  -2742.348640071     
1.090084718397e-06  1.090084755821e-06  9.577867382538e-07  0.9787891228589  1.090084643117e-06  -6321.263610821     
5.419673280836e-07  5.419673466903e-07  4.761915387563e-07  0.5393624896542  5.419672906562e-07  -13326.66584827     
2.491643472483e-09  2.491643558034e-09  2.189245548734e-09  0.9964576352432  2.491643300422e-09  -14848.0449886      
1.261046309265e-13  1.261056935817e-13  1.108002578576e-13  0.9999502263562  1.261056979846e-13  -14952.08733357     
6.411732059872e-18  6.307009682591e-18  0.0                 0.9999499864092  6.305285156254e-18  -14952.09262594     
Optimization terminated successfully.


In [121]:
scipy.optimize.OptimizeResult

scipy.optimize.optimize.OptimizeResult

In [122]:
print(res)

     con: array([], dtype=float64)
     fun: -14952.09262594362
 message: 'Optimization terminated successfully.'
     nit: 6
   slack: array([6.90575689e-06, 8.21125499e+06, 2.23765383e-05, 3.13715539e+06,
       6.87867400e+05, 1.79864653e+05, 1.82174294e+04, 1.45747944e+03,
       8.48683798e+03, 1.41955874e+04, 3.56505268e+02, 1.34096609e-08,
       2.24673755e-08])
  status: 0
 success: True
       x: array([866637.69047215,  67810.63570914,  47511.12948845,  18040.54432336])


In [123]:
Total_conv=866637.69047218*0.01649546+67810.63570914*0.00673206+47511.12948845*0.00210477+18040.54432336*0.00554307
Total_conv

14952.09262594419

In [124]:
adwords_conv=866637.69047218*0.01649546
adwords_conv

14295.587357676226

In [125]:
r1=adwords_conv/Total_conv
r1

0.9560927500456474

In [34]:
bing_conv=67810.63570914*0.00673206

In [35]:
r2=bing_conv/Total_conv
r2

NameError: name 'Total_conv' is not defined

In [ ]:
DCM_conv=47511.12948845*0.00210477
DCM_conv

In [ ]:
r3=DCM_conv/Total_conv
r3

In [ ]:
FB_conv=18040.54432336*0.00554307
FB_conv

In [ ]:
r4=FB_conv/Total_conv
r4

In [ ]:
Total_clicks=866637.69047218*.20812002+67810.63570914*0.27602498+47511.12948845*0.04120044+18040.54432336*0.49814672
Total_clicks

In [36]:
adwords_clicks=866637.69047218*.20812002

In [37]:
cr1=adwords_clicks/Total_clicks
cr1

NameError: name 'Total_clicks' is not defined

In [ ]:
bing_clicks=67810.63570914*0.27602498

In [ ]:
cr2=bing_clicks/Total_clicks
cr2

In [ ]:
DCM_clicks=47511.12948845*0.04120044

In [ ]:
cr3=DCM_clicks/Total_clicks
cr3

In [ ]:
FB_clicks=18040.54432336*0.49814672

In [38]:
cr4=FB_clicks/Total_clicks
cr4

NameError: name 'FB_clicks' is not defined

In [39]:
Total_imp=866637.69047218*10.6287265+67810.63570914*14.7469492+47511.12948845*87.0776054+18040.54432336*43.6720415
Total_imp

15136277.77271877

In [40]:
adwords_imp=866637.69047218*10.6287265

In [41]:
Ir1=adwords_imp/Total_imp
Ir1

0.6085548326301584

In [42]:
bing_imp=67810.63570914*14.7469492


In [43]:
Ir2=bing_imp/Total_imp
Ir2

0.06606644084087616

In [44]:
DCM_imp=47511.12948845*87.0776054

In [45]:
Ir3=DCM_imp/Total_imp
Ir3

0.2733271315329752

In [46]:
Fb_imp=18040.54432336*43.6720415

In [47]:
Ir4=Fb_imp/Total_imp
Ir4

0.05205159499599029

In [48]:
c = [-0.00887773,-0.00336614,-0.00026383,-0.00346332]
A= [[1.0,1.0,1.0,1.0],[-13.0881685,0.0,0.0,0.0],[0.0,-15.1430304,0.0,0.0],[0.0,0.0,-83.4449666,0.0],[0.0,0.0,0.0,-47.5492224],
    [-0.1562806,0.0,0.0,0.0],[0.0,-0.22021831,0.0,0.0],[0.0,0.0,-0.04360438,0.0],[0.0,0.0,0.0,-0.79059825],[-0.00887773,0.0,0.0,0.0],[0.0,-0.00336614,0.0,0.0],[0.0,0.0,-0.00026383,0.0],[0.0,0.0,0.0,-0.00346332]]
b= [1000000.0,-1000000.0,-1000000.0,-1000000.0,-100000.0,-500.0,-500.0,-500.0,-500.0,-100.0,-100.0,-100.0,-100.0]

In [49]:
res = linprog(c,A_ub=A,b_ub=b,bounds=(x1_bounds,x2_bounds,x3_bounds,x4_bounds),options={"disp": True},method='interior-point')

Primal Feasibility  Dual Feasibility    Duality Gap         Step             Path Parameter      Objective          
1.0                 1.0                 0.98402898          -                1.0                 -1100.607625377     
5.228697059655e-05  5.228697015459e-05  5.703069363561e-05  0.9999477130294  5.22869805856e-05   -1352.477211015     
1.56909405156e-06   1.569094038297e-06  1.711449735264e-06  0.9700372533392  1.569094351324e-06  -2370.708157416     
7.526453015892e-07  7.526452952273e-07  8.209288671623e-07  0.5574724970468  7.526454453766e-07  -4639.789684402     
5.769061501017e-09  5.769061452269e-09  6.292458255841e-09  0.9929567344912  5.76906260317e-09   -5049.798648124     
2.951253859388e-13  2.95125476253e-13   3.218883493084e-13  0.9999502803188  2.951255359172e-13  -5092.479780761     
1.494693346264e-17  1.475794133075e-17  2.775557561563e-17  0.999949994311   1.475627698127e-17  -5092.482076936     
Optimization terminated successfully.


In [50]:
print(res)

     con: array([], dtype=float64)
     fun: -5092.482076936327
 message: 'Optimization terminated successfully.'
     nit: 6
   slack: array([6.07513357e-06, 5.88512317e+06, 2.10105209e-05, 3.06283086e+07,
       1.27293760e+06, 8.17125097e+04, 1.40425522e+04, 1.60274533e+04,
       2.23277563e+04, 4.57019236e+03, 1.22289721e+02, 1.46391699e-09,
       3.51440121e-09])
  status: 0
 success: True
       x: array([526057.03891712,  66036.98028771, 379031.95239914,  28874.02838996])


In [51]:
Total_conv=526057.03891712*0.00887773+66036.98028771*0.00336614+379031.95239914*0.00026383+28874.02838996*0.00346332
Total_conv

5092.482076936337

In [52]:
ad_conv=526057.03891712*0.00887773
ad_conv

4670.192356105684

In [53]:
r1=ad_conv/Total_conv
r1

0.9170758552606032

In [54]:
bing_conv=66036.98028771*0.00336614

In [55]:
r2=bing_conv/Total_conv
r2

0.04365056517968204

In [56]:
DCM_conv=379031.95239914*0.00026383

In [57]:
r3=DCM_conv/Total_conv
r3

0.019636789779656057

In [58]:
Fb_conv=28874.02838996*0.00346332

In [59]:
r4=Fb_conv/Total_conv
r4

0.019636789780058842

In [60]:
Total_clicks=526057.03891712*0.1562806+66036.98028771*0.22021831+379031.95239914*0.04360438+28874.02838996*0.79059825
Total_clicks

136110.27147276036

In [61]:
adwords_clicks=526057.03891712*0.1562806

In [62]:
cr1=adwords_clicks/Total_clicks
cr1

0.6040140011964047

In [63]:
bing_clicks=66036.98028771*0.22021831

In [64]:
cr2=bing_clicks/Total_clicks
cr2

0.10684389972268331

In [65]:
DCM_clicks=379031.95239914*0.04360438

In [66]:
cr3=DCM_clicks/Total_clicks
cr3

0.12142693645175513

In [67]:
Fb_clicks=28874.02838996*0.79059825

In [68]:
cr4=Fb_clicks/Total_clicks
cr4

0.16771516262915684

In [69]:
[-0.00887773,-0.00336614,-0.00026383,-0.00346332]
A= [[1.0,1.0,1.0,1.0],[-13.0881685,0.0,0.0,0.0],[0.0,-15.1430304,0.0,0.0],[0.0,0.0,-83.4449666,0.0],[0.0,0.0,0.0,-47.5492224],
    [-0.1562806,0.0,0.0,0.0],[0.0,-0.22021831,0.0,0.0],[0.0,0.0,-0.04360438,0.0],[0.0,0.0,0.0,-0.79059825],[-0.00887773,0.0,0.0,0.0],[0.0,-0.00336614,0.0,0.0],[0.0,0.0,-0.00026383,0.0],[0.0,0.0,0.0,-0.00346332]]
b= [1000000.0,-1000000.0,-1000000.0,-1000000.0,-100000.0,-500.0,-500.0,-500.0,-500.0,-100.0,-100.0,-100.0,-100.0]

In [70]:
Total_imp=526057.03891712*13.0881685+66036.98028771*15.1430304+379031.95239914*83.4449666+28874.02838996*47.5492224
Total_imp

40886369.371756464

In [71]:
adwords_imp=526057.03891712*13.0881685

In [72]:
Ir1=adwords_imp/Total_imp
Ir1

0.16839654074823374

In [73]:
bing_imp=66036.98028771*15.1430304

In [74]:
Ir2=bing_imp/Total_imp
Ir2

0.024458028809762073

In [75]:
DCM_imp=379031.95239914*83.4449666

In [76]:
Ir3=DCM_imp/Total_imp
Ir3

0.7735660831290946

In [77]:
Fb_imp=28874.02838996*47.5492224

In [78]:
Ir4=Fb_imp/Total_imp
Ir4

0.03357934731290965

In [126]:
print(A*res.x)

[[ 8.66637690e+05  6.78106357e+04  4.75111295e+04  1.80405443e+04]
 [-9.21125499e+06  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -1.00000000e+06  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -4.13715539e+06  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -7.87867400e+05]
 [-1.80364653e+05  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -1.87174294e+04  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.95747944e+03  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -8.98683798e+03]
 [-1.42955874e+04  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -4.56505268e+02  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.00000000e+02  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -1.00000000e+02]]


In [127]:
import numpy as np

In [130]:
np.transpose(np.array(c))*res.x

array([-14295.58735768,   -456.50526823,   -100.00000001,   -100.00000002])